============= phase: takeoff=============
====== self.motor_rpms.shape (4,) ======
====== self.motor_rpms.shape (4,) ======
====== self.motor_rpms.shape (4,) ======
====== self.motor_rpms.shape (4,) ======
====== self.motor_rpms.shape (4,) ======
====== self.motor_rpms.shape (4,) ======
====== self.motor_rpms.shape (4,) ======
====== self.motor_rpms.shape (4,) ======
====== self.motor_rpms.shape (4,) ======
====== self.motor_rpms.shape (4,) ======
takeoff
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 619, in run_mpc_thread
    self.send_optimized_traj()
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 405, in send_optimized_traj
    self.pub_optimized_traj.publish(msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 9.194 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.002 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.000 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.000 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
============= phase: takeoff=============
Ошибка при выполнении MPC: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389
Traceback (most recent call last):
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 563, in run_mpc_thread
    self.send_msg_to_client("mpc_on")# на всякий случай если сообщене не дойдет с одного раза,
  File "/home/vor/ros2_px4_offboard_example_ws/install/px4_offboard/lib/python3.10/site-packages/px4_offboard/dynamics_drone_control.py", line 383, in send_msg_to_client
    self.server_pub.publish(server_msg)
  File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/publisher.py", line 70, in publish
    self.__publisher.publish(msg)
rclpy._rclpy_pybind11.RCLError: Failed to publish: publisher's context is invalid, at ./src/rcl/publisher.c:389

[mpc_control_loop] END phase: takeoff, duration: 0.001 s
